### ISSUE TITLE
Contour custom list error

### ISSUE THREAD

**Issue by Shuffle20** [endarthur/os#25]
Hi,
I'm trying to use the "Custom list" Contour option entering values separated by comma (as I always did with version 0.1.2f) , but I get the following error: 

_Traceback (most recent call last): File "C:\Program Files\OpenStereo\pkgs\openstereo\os_base.py", line 2002, in item.dialog_ui.apply.clicked.connect(lambda: apply_action()) File "C:\Program Files\OpenStereo\pkgs\openstereo\ui\ui_interface.py", line 132, in apply_action main_window.plot_data() File "C:\Program Files\OpenStereo\pkgs\openstereo\os_base.py", line 1357, in plot_data self.plot_tree_item(item) File "C:\Program Files\OpenStereo\pkgs\openstereo\os_base.py", line 1335, in plot_tree_item self.projection_plot.plot_data(plot_item) File "C:\Program Files\OpenStereo\pkgs\openstereo\os_plot.py", line 414, in plot_data plot_item.n, File "C:\Program Files\OpenStereo\pkgs\openstereo\os_plot.py", line 674, in plot_contours b"[^-\\d\\.]+", contour_settings["intervals"] File "re.py", line 212, in split TypeError: cannot use a bytes pattern on a string-like object_

Thanks

**Comment by endarthur** [comment]
Hi @Shuffle20 ,

I'll check later today, I'm fairly sure it's a bug from when I went from python 2 to 3.

**Comment by endarthur** [comment]
Hi @Shuffle20 !
Should be fixed in the new release:
https://github.com/spamlab-iee/os/releases/tag/v2.0b12

**Comment by Shuffle20** [comment]
works perfectly, thank you very much !
